export const BROWSE_ACTIONS = {
  SET_BROWSE_WORLD: 'SET_BROWSE_WORLD',
  SET_BROWSE_STORY: 'SET_BROWSE_STORY',
  CLEAR_BROWSE_INFO: 'CLEAR_BROWSE_INFO',
  CHANGE_BROWSE_WORLD: 'CHANGE_BROWSE_WORLD',
  REQUEST_START: 'REQUEST_START_BROWSE_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_BROWSE_ACTIONS',
}