export const BROWSE_ACTIONS = {
  GET_BROWSE_WORLD: 'GET_BROWSE_WORLD',
  SET_BROWSE_WORLD: 'SET_BROWSE_WORLD',
  GET_BROWSE_STORY: 'GET_BROWSE_STORY',
  SET_BROWSE_STORY: 'SET_BROWSE_STORY',
  CHANGE_BROWSE_WORLD: 'CHANGE_BROWSE_WORLD',
  GET_WORLD_STORIES: 'GET_BROWSE_WORLD_STORIES',
  SET_WORLD_STORIES: 'SET_BROWSE_WORLD_STORIES',
  REQUEST_START: 'REQUEST_START_BROWSE_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_BROWSE_ACTIONS',
}