export const CREATE_PAGE_ACTIONS = {
  SET_CREATE_WORLD: 'SET_CREATE_PAGE_WORLD',
  SET_CREATE_STORY: 'SET_CREATE_PAGE_STORY',
  CLEAR_CREATE_STORY: 'CLEAR_CREATE_STORY',
  CHANGE_CREATE_WORLD: 'CHANGE_CREATE_WORLD',
  SET_FORM_TYPE: 'SET_CREATE_FORM_TYPE',
  CLEAR_FORM_INFO: 'CLEAR_FORM_INFO',
  REQUEST_START: 'REQUEST_START_CHANGE_PAGE_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_CHANGE_PAGE_ACTIONS',
}