export const CREATE_PAGE_ACTIONS = {
  SET_CREATE_WORLD: 'SET_CREATE_PAGE_WORLD',
  SET_CREATE_STORY: 'SET_CREATE_PAGE_STORY',
  CHANGE_CREATE_WORLD: 'CHANGE_CREATE_WORLD',
  SET_FORM_TYPE_WORLD: 'SET_CREATE_FORM_TYPE_WORLD',
  SET_FORM_TYPE_STORY: 'SET_CREATE_FORM_TYPE_STORY',
  REQUEST_START: 'REQUEST_START_CHANGE_PAGE_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_CHANGE_PAGE_ACTIONS',
}