export const LOCATION_ACTIONS = {
  GET_LOCATIONS: 'GET_LOCATIONS',
  SET_LOCATIONS: 'SET_LOCATIONS',
  REQUEST_START: 'REQUEST_START_LOCATION_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_LOCATION_ACTIONS',
}