export const LOCATION_ACTIONS = {
  GET_LOCATIONS: 'GET_LOCATIONS',
  SET_LOCATIONS: 'SET_LOCATIONS',
  GET_LOCATIONS_IN_WORLD: 'GET_LOCATIONS_IN_WORLD',
  SET_LOCATIONS_IN_WORLD: 'SET_LOCATIONS_IN_WORLD',
  CLEAR_LOCATIONS_IN_WORLD: 'CLEAR_LOCATIONS_IN_WORLD',
  GET_LOCATIONS_IN_STORY: 'GET_LOCATIONS_IN_STORY',
  SET_LOCATIONS_IN_STORY: 'SET_LOCATIONS_IN_STORY',
  CLEAR_LOCATIONS_IN_STORY: 'CLEAR_LOCATIONS_IN_STORY',
  CREATE_NEW_LOCATION: 'CREATE_NEW_LOCATION',
  REQUEST_START: 'REQUEST_START_LOCATION_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_LOCATION_ACTIONS',
}