export const RECENTLY_ADDED_ACTIONS = {
  GET_RECENTLY_ADDED: 'GET_RECENTLY_ADDED',
  SET_RECENTLY_ADDED: 'SET_RECENTLY_ADDED',
  REQUEST_START: 'REQUEST_START_RECENTLY_ADDED_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_RECENTLY_ADDED_ACTIONS',
}