export const SEARCH_ACTIONS = {
  REQUEST_START: 'REQUEST_START_SEARCH_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_SEARCH_ACTIONS',
  SET_SEARCH_RESULTS: 'SET_SEARCH_RESULTS',
  SUBMIT_SEARCH_QUERY: 'SUBMIT_SEARCH_QUERY',
  SUBMIT_ADVANCED_SEARCH_QUERY: 'SUBMIT_ADVANCED_SEARCH_QUERY',
}