export const STORY_ACTIONS = {
  GET_STORIES: 'GET_STORIES',
  SET_STORIES: 'SET_STORIES',
  SET_STORIES_IN_WORLD: 'SET_STORIES_IN_WORLD',
  REQUEST_START: 'REQUEST_START_STORY_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_STORY_ACTIONS',
}