export const STORY_ACTIONS = {
  GET_STORIES: 'GET_STORIES',
  SET_STORIES: 'SET_STORIES',
  SET_STORIES_IN_WORLD: 'SET_STORIES_IN_WORLD',
  GET_STORY_DETAILS: 'GET_STORY_DETAILS',
  SET_STORY_DETAILS: 'SET_STORY_DETAILS',
  GET_STORY_GENRES: 'GET_STORY_GENRES',
  SET_STORY_GENRES: 'SET_STORY_GENRES',
  SUBMIT_NEW_STORY: 'SUBMIT_NEW_STORY',
  REQUEST_START: 'REQUEST_START_STORY_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_STORY_ACTIONS',
}