export const WORLD_ACTIONS = {
  GET_WORLDS: 'GET_WORLDS',
  SET_WORLDS: 'SET_WORLDS',
  POST_CREATE_WORLD: 'POST_CREATE_WORLD',
  REQUEST_START: 'REQUEST_START_WORLD_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_WORLD_ACTIONS',
}