export const WORLD_ACTIONS = {
  GET_WORLDS: 'GET_WORLDS',
  SET_WORLDS: 'SET_WORLDS',
  POST_NEW_WORLD: 'POST_NEW_WORLD',
  SUBMIT_NEW_WORLD: 'SUBMIT_NEW_WORLD',
  GET_WORLD_DETAILS: 'GET_WORLD_DETAILS',
  SET_WORLD_DETAILS: 'SET_WORLD_DETAILS',
  SUBMIT_WORLD_EDITS: 'SUBMIT_WORLD_EDITS',
  DELETE_WORLD: 'DELETE_WORLD',
  CLEAR_WORLD_DETAILS: 'CLEAR_WORLD_DETAILS',
  REQUEST_START: 'REQUEST_START_WORLD_ACTIONS',
  REQUEST_DONE: 'REQUEST_DONE_WORLD_ACTIONS',
}